[project]
name = "lockstep"
version = "0.1.0"
dependencies = [
    "antlr4-python3-runtime",
]

[project.scripts]
lockstep-frontend = "lockstep_frontend:run_cli"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[tool.pytest.ini_options]
addopts = "-q -ra"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["."]
omit = [
    "tests/*",
    "LockstepLexer.py",
    "LockstepListener.py",
    "LockstepParser.py",
    "LockstepVisitor.py",
]

[tool.coverage.report]
show_missing = true
